Hot reloading
ya-porto/Yaporto-rpg pull request #36
Opened 2021-06-06 18:56 UTC by Jefrry

Пока без обновления страницы

2021-06-07 04:36 UTC, ammodit-p requested changes

2021-06-07 04:36 UTC, ammodit-p commented on package.json
>      "build": "NODE_ENV=production NODE_PATH=. npm run clean && webpack --mode production",
у нас должна быть прол сборка и дев сборка. в том числе и для запуска сервака (не забудь, что скрипт start у нас в Докере используется)

без разницы как оно будет называться, но обыкновенно скрипт дев-сборки называют dev
и внутри как раз запускают срипт сборки в ватч-режиме + если надо сервер с ватч-режимом

то есть должно быть что-то вроде
build: ...
start: ...
dev: ...
start:watch: ...

2021-06-07 04:36 UTC, ammodit-p commented on src/client/index.tsx
> +	}
я как раз влила изменения сервисворкера, надо подтянуть и разрезолвить конфликт

2021-06-07 04:37 UTC, ammodit-p commented
обязательно верни скрипт start без дев-режима для докера

2021-06-08 11:29 UTC, Jefrry commented
Сделал задержку перезагрузки страницы 0,8 сек. Это нужно чтобы дождаться ребилда. Значение можем изменить если что

2021-06-08 20:40 UTC, merged