Добавлена инициализация клиентского редакса от серверного
ya-porto/Yaporto-rpg pull request #37
Opened 2021-06-09 13:43 UTC by Miroga64

2021-06-09 15:35 UTC, Jefrry requested changes
Пофикси линтер. Не забудь аккуратно спулить с основной ветки

2021-06-09 15:35 UTC, Jefrry commented on src/components/App.tsx
> +store.subscribe(() => console.log(store.getState()));
Не понял, зачем это здесь?

2021-06-09 15:35 UTC, Jefrry commented on src/redux/rootStore.ts
> +			initialState: initialState,
Не надо класть это в стейт роутера. Его вообще вырезать надо

2021-06-09 15:35 UTC, Jefrry commented on src/redux/storeCharacter.ts
> +console.log(initialState);
Убери все консоль логи

2021-06-09 15:35 UTC, Jefrry commented on src/redux/storeCharacter.ts
> +const initialState = isServer ? {} : window.__INITIAL_STATE__.router.initialState;
Попробуй так `window.__INITIAL_STATE__ || {}`

2021-06-09 15:35 UTC, Jefrry commented on src/redux/storeCharacter.ts
> +const initialState = isServer ? {} : window.__INITIAL_STATE__.router.initialState;
Вообще это можно вынести в отдельный файл раз идёт проверка в больше чем двух местах

2021-06-10 07:13 UTC, Miroga64 commented on src/redux/rootStore.ts
> +			initialState: initialState,
Ника сказала будет вырезать это, поэтому пока так оставил

2021-06-10 09:00 UTC, Jefrry approved these changes

2021-06-10 12:38 UTC, ammodit-p requested changes

2021-06-10 12:38 UTC, ammodit-p commented on src/server/server-render-middleware.tsx
> +	console.log(`<!doctype html>${html}`);
убери консоль лог

2021-06-10 19:20 UTC, ammodit-p commented on src/redux/stateFromSSR.ts
> +export const initialState = isServer ? {} : window.__INITIAL_STATE__.router.initialState;
у тебя в двух местах в коде разные сущности названы initialState
нужны разные названия переменным

2021-06-15 10:34 UTC, merged