Sprint7 3
ya-porto/Yaporto-rpg pull request #39
Opened 2021-06-12 09:26 UTC by ammodit-p

2021-06-12 16:57 UTC, Jefrry approved these changes

2021-06-12 16:57 UTC, Jefrry commented on src/client/index.tsx
>  	if ('serviceWorker' in navigator) {
Куда делся SW?

2021-06-13 13:33 UTC, ammodit-p commented on src/client/index.tsx
>  	if ('serviceWorker' in navigator) {
в смысле делся? он на месте

2021-06-13 13:35 UTC, ammodit-p commented on src/client/index.tsx
>  	if ('serviceWorker' in navigator) {
гит не весь файл в диффе отображает. тут слева есть стрелочки, чтоб развернуть и посмотреть полностью код

2021-06-17 17:55 UTC, eshturman requested changes

2021-06-17 17:55 UTC, eshturman commented on src/redux/rootStore.ts
> +/* eslint-disable */
лучше тогда eslint-disbale-next-line

2021-06-17 17:55 UTC, eshturman commented on src/server/authMiddleware.ts
> +	/* eslint-disable */
тоже самое

2021-06-17 17:55 UTC, eshturman commented on src/server/authMiddleware.ts
> +	} catch (err) {
Обработать ошибку

2021-06-17 18:05 UTC, merged