Sprint7 40
ya-porto/Yaporto-rpg pull request #50
Opened 2021-06-16 21:09 UTC by ammodit-p

2021-06-16 21:11 UTC, ammodit-p commented
тут все еще часть кода из ветки 7-3 с миддлварой.

2021-06-17 07:45 UTC, Jefrry commented on src/pages/profile/index.ts
> +export default Profile;
Почему здесь default стало?

2021-06-17 07:45 UTC, Jefrry commented on src/pages/profile/profile.tsx
> +export default connect(mapStateToProps)(Profile);
Помечу, чтоб на синке спросить что это

2021-06-17 07:45 UTC, Jefrry commented on src/pages/signin/signin.tsx
> +		})['catch'](e => {
Можно же просто `.catch`

2021-06-17 07:45 UTC, Jefrry commented on src/pages/profile/profile.tsx
> +const document = getDocument();
Чет я не нашёл где это используется

2021-06-17 17:49 UTC, ammodit-p commented on src/pages/profile/index.ts
> +export default Profile;
потому что connect можно экспортировать только дефолтно.

2021-06-17 17:50 UTC, ammodit-p commented on src/pages/profile/profile.tsx
> +export default connect(mapStateToProps)(Profile);
спросил)

2021-06-17 17:50 UTC, ammodit-p commented on src/pages/signin/signin.tsx
> +		})['catch'](e => {
а это линтер ща меня исправил. надо вернуть как было

2021-06-17 17:51 UTC, ammodit-p commented on src/pages/profile/profile.tsx
> +const document = getDocument();
в смене аватара.

2021-06-19 06:00 UTC, eshturman requested changes

2021-06-19 06:00 UTC, eshturman commented on src/pages/profile/profile.tsx
> +			this.showUserInfo()
для читаемости лучше сделать через arrow function

2021-06-20 19:22 UTC, merged