Sprint7 10 Oauth
ya-porto/Yaporto-rpg pull request #52
Opened 2021-06-17 10:15 UTC by Jefrry

2021-06-17 18:01 UTC, ammodit-p commented on src/pages/main/main.tsx
> +
я не совсем поняла этой логики

почему этот запрос в main в CDM?

2021-06-17 18:07 UTC, Jefrry commented on src/pages/main/main.tsx
> +
После подтверждения Яндекс аккаунта для последнего этапа авторизации он редиректит на _localhost:3000/?code=228_, и код этот нужен для POST запроса

2021-06-19 06:01 UTC, eshturman requested changes

2021-06-19 06:01 UTC, eshturman commented on src/pages/signin/signin.tsx
> +				const URL = `https://oauth.yandex.ru/authorize?response_type=code&client_id=${data.service_id}&redirect_uri=${redirect}`;
Лучше вынести адрес в отдельный файл

2021-06-20 11:32 UTC, merged