Добавил модалки смерти и победы.
ya-porto/Yaporto-rpg pull request #63
Opened 2021-06-29 07:37 UTC by Jefrry

1. Не смог добавить анимацию показа модалки
-В ветке спринт8 отсутствует пакет для анимации
-После установки пакета и использовании его, сервер начинает ругаться на неверное использование и/или подключение
2. Слежу за изменениями стора через _subscribe_. Скорее всего этого непроизводительно. Но для другого способа нужно переписывать все на функциональный компонент.
3. знаю, что тянуть стор из файла персонажа неправильно, но в данной архитектуре это наиболее релевантный способ

2021-06-29 10:02 UTC, ammodit-p commented
чтобы следить за изменениями стора мы используем кастомную функцию mapStateToProps. и connect из реакт-редакс, посмотри как на страницах это сдалено.
если можно это сделать в файлах игры - лучше если у нас будет общий подходд на проекте

2021-06-29 10:06 UTC, ammodit-p requested changes

2021-06-29 10:06 UTC, ammodit-p commented on server-app/src/components/game/character.tsx
> +						store.dispatch(toggleModalWin(true))
не стоит изменение показа модалки класть в стор

в сторе можно хранить состояние - умер? не умер? выиграл? не выиграл? или что-то вроде этого
на странице самой игры слушать стор и в зависимости от пропса (который мы получаем из стора через mapStateToProps) триггерить рендер модалки

2021-06-29 10:06 UTC, ammodit-p commented on server-app/src/pages/game/game.tsx
> +					<GameCanvas />
тут нет привязки к стору через connect

2021-06-29 10:06 UTC, ammodit-p commented on server-app/src/redux/gameSlice.ts
> +		toggleModalDeath: (state: any, action: any) => {
+ к выше сказанному. логика показа модалки должна быть на стороне страницы/компонента. а стор хранит только информацию по самой игре

2021-06-30 18:09 UTC, ammodit-p approved these changes

2021-07-04 16:05 UTC, eshturman approved these changes

2021-07-05 09:09 UTC, merged